#!/bin/sh

REL="$(dirname "$0")"
ABS="$(cd "$REL"; pwd)"

JIRI="$ABS/.."
JAZZ="$JIRI/jazz"
LIBGIT2="$JAZZ/foreign/libgit2"
GAMBIT="$JAZZ_GAMBITDIR"

BUILD="build"
INSTALL="install"
SETUP="setup"

NAME="$1Setup"

CFILES="$BUILD/features.c $BUILD/crash.c $BUILD/git.c $BUILD/geometry.c $BUILD/window.c $BUILD/view.c $BUILD/windows.c $BUILD/run.c"
OFILES="$BUILD/features.o $BUILD/crash.o $BUILD/git.o $BUILD/geometry.o $BUILD/window.o $BUILD/view.o $BUILD/windows.o $BUILD/run.o"

if [ ! -d $BUILD ]; then
    mkdir $BUILD
fi
if [ ! -d $INSTALL ]; then
    mkdir $INSTALL
fi
if [ ! -d $SETUP ]; then
    mkdir $SETUP
fi

windres --input $ABS/setup.rc --output $BUILD/setup.res --output-format=coff
gsc -c -o $BUILD $ABS/features
gsc -c -o $BUILD $ABS/crash
gsc -c -o $BUILD $ABS/git
gsc -c -o $BUILD $ABS/geometry
gsc -c -o $BUILD $ABS/window
gsc -c -o $BUILD $ABS/view
gsc -c -o $BUILD $ABS/windows
gsc -c -o $BUILD $ABS/run
gsc -link -o $BUILD $CFILES
gsc -cc-options "-I$LIBGIT2/include" -obj $CFILES $BUILD/run_.c
gcc -L$GAMBIT/lib -L$LIBGIT2/lib $OFILES $BUILD/run_.o $BUILD/setup.res -mwindows -lgit2 -lgambc -lws2_32 -lgdi32 -o $INSTALL/Install
cp $LIBGIT2/lib/libgit2.dll $INSTALL
