#!/bin/sh

REL="$(dirname "$0")"
ABS="$(cd "$REL"; pwd)"

JIRI="$ABS/.."
JAZZ="$JIRI/jazz"
FOREIGN="$JAZZ/foreign"
LIBGIT2="$FOREIGN/libgit2"
OPENSSL="$FOREIGN/openssl"
GAMBIT="$GAMBITDIR"

ROOT="release"
BUILD="$ROOT/build"
INSTALL="$ROOT/install"
SETUP="$ROOT/setup"

MODE="windows"
case "$1" in
    "-console" )
        MODE="console"
        ;;
    "-windows" )
        MODE="windows"
        ;;
esac

CFILES="$BUILD/settings.c $BUILD/features.c $BUILD/crash.c $BUILD/git.c $BUILD/windows.c $BUILD/base.c $BUILD/geometry.c $BUILD/color.c $BUILD/font.c $BUILD/window.c $BUILD/draw.c $BUILD/view.c $BUILD/setup.c $BUILD/main.c"
OFILES="$BUILD/settings.o $BUILD/features.o $BUILD/crash.o $BUILD/git.o $BUILD/windows.o $BUILD/base.o $BUILD/geometry.o $BUILD/color.o $BUILD/font.o $BUILD/window.o $BUILD/draw.o $BUILD/view.o $BUILD/setup.o $BUILD/main.o"

if [ ! -d $ROOT ]; then
    mkdir $ROOT
fi
if [ ! -d $BUILD ]; then
    mkdir $BUILD
fi
if [ ! -d $INSTALL ]; then
    mkdir $INSTALL
fi
if [ ! -d $SETUP ]; then
    mkdir $SETUP
fi

windres --input $ABS/setup.rc --output $BUILD/setup.res --output-format=coff
gsc -c -o $BUILD settings
gsc -c -o $BUILD $ABS/features
gsc -c -o $BUILD $ABS/crash
gsc -c -o $BUILD $ABS/git
gsc -c -o $BUILD $ABS/windows
gsc -c -o $BUILD $ABS/base
gsc -c -o $BUILD $ABS/geometry
gsc -c -o $BUILD $ABS/color
gsc -c -o $BUILD $ABS/font
gsc -c -o $BUILD $ABS/window
gsc -c -o $BUILD $ABS/draw
gsc -c -o $BUILD $ABS/view
gsc -c -o $BUILD $ABS/setup
gsc -c -o $BUILD $ABS/main
gsc -link -o $BUILD $CFILES
gsc -cc-options "-I$LIBGIT2/include" -obj $CFILES $BUILD/main_.c
gcc -L$GAMBIT/lib -L$LIBGIT2/lib $OFILES $BUILD/main_.o $BUILD/setup.res -m$MODE -lgit2 -lgambc -lws2_32 -lgdi32 -lole32 -luuid -o $INSTALL/Install
cp $LIBGIT2/lib/libgit2.dll $INSTALL
cp $OPENSSL/lib/libeay32.dll $INSTALL
cp $OPENSSL/lib/ssleay32.dll $INSTALL
