#!/bin/sh

REL="$(dirname "$0")"
ABS="$(cd "$REL"; pwd)"

JIRI="$ABS/.."
JAZZ="$JIRI/jazz"
FOREIGN="$JAZZ/foreign"
LIBGIT2="$FOREIGN/libgit2"
OPENSSL="$FOREIGN/openssl"
GAMBIT="$GAMBITDIR"

ROOT="release"
BUILD="$ROOT/build"
SETUP="$ROOT/setup"
INSTALL="$ROOT/install"

CBASE="$BUILD/settings.c $BUILD/features.c $BUILD/windows.c $BUILD/crash.c $BUILD/base.c $BUILD/geometry.c $BUILD/color.c $BUILD/font.c $BUILD/structure.c"
OBASE="$BUILD/settings.o $BUILD/features.o $BUILD/windows.o $BUILD/crash.o $BUILD/base.o $BUILD/geometry.o $BUILD/color.o $BUILD/font.o $BUILD/structure.o"

CFILES="$CBASE $BUILD/git.c $BUILD/window.c $BUILD/draw.c $BUILD/view.c $BUILD/work.c"
OFILES="$OBASE $BUILD/git.o $BUILD/window.o $BUILD/draw.o $BUILD/view.o $BUILD/work.o"

LBASE="-lgambc -lws2_32 -lgdi32 -lole32 -luuid"

if [ ! -d $ROOT ]; then
    mkdir $ROOT
fi
if [ ! -d $BUILD ]; then
    mkdir $BUILD
fi
if [ ! -d $SETUP ]; then
    mkdir $SETUP
fi
if [ ! -d $INSTALL ]; then
    mkdir $INSTALL
fi

# Common
gsc -c -o $BUILD settings
gsc -c -o $BUILD $ABS/features
gsc -c -o $BUILD $ABS/windows
gsc -c -o $BUILD $ABS/crash
gsc -c -o $BUILD $ABS/git
gsc -c -o $BUILD $ABS/base
gsc -c -o $BUILD $ABS/geometry
gsc -c -o $BUILD $ABS/color
gsc -c -o $BUILD $ABS/font
gsc -c -o $BUILD $ABS/window
gsc -c -o $BUILD $ABS/draw
gsc -c -o $BUILD $ABS/view
gsc -c -o $BUILD $ABS/structure
gsc -c -o $BUILD $ABS/work
gsc -c -o $BUILD $ABS/setup
gsc -c -o $BUILD $ABS/install
gsc -c -o $BUILD $ABS/launch

# Setup
windres --input $ABS/setup.rc --output $BUILD/setup.res --output-format=coff
gsc -link -o $BUILD $CFILES $BUILD/setup.c
gsc -cc-options "-I$LIBGIT2/include" -obj $CFILES $BUILD/setup.c $BUILD/setup_.c
gcc -L$GAMBIT/lib -L$LIBGIT2/lib $OFILES $BUILD/setup.o $BUILD/setup_.o $BUILD/setup.res -mwindows -lgit2 $LBASE -o $SETUP/Setup
cp $LIBGIT2/lib/libgit2.dll $SETUP
cp $OPENSSL/lib/libeay32.dll $SETUP
cp $OPENSSL/lib/ssleay32.dll $SETUP

# Install
windres --input $ABS/install.rc --output $BUILD/install.res --output-format=coff
gsc -link -o $BUILD $CFILES $BUILD/install.c
gsc -cc-options "-I$LIBGIT2/include" -obj $CFILES $BUILD/install.c $BUILD/install_.c
gcc -L$GAMBIT/lib -L$LIBGIT2/lib $OFILES $BUILD/install.o $BUILD/install_.o $BUILD/install.res -mwindows -lgit2 $LBASE -o $INSTALL/Install
cp $LIBGIT2/lib/libgit2.dll $INSTALL
cp $OPENSSL/lib/libeay32.dll $INSTALL
cp $OPENSSL/lib/ssleay32.dll $INSTALL

# Launch
windres --input $ABS/launch.rc --output $BUILD/launch.res --output-format=coff
gsc -link -o $BUILD $CBASE $BUILD/launch.c
gsc -obj $CBASE $BUILD/launch.c $BUILD/launch_.c
gcc -L$GAMBIT/lib $OBASE $BUILD/launch.o $BUILD/launch_.o $BUILD/launch.res -mwindows $LBASE -o $INSTALL/Launch
